name: amap_all_fluttify_example
description: Demonstrates how to use the amap_all_fluttify plugin.
publish_to: 'none'

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  demo_widgets: ^0.0.3
  decorated_flutter: ^0.12.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  amap_all_fluttify:
    path: ../

flutter:
  uses-material-design: true